name: Export and Publish
env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
  ITCH_GAME: ${{ secrets.ITCH_GAME }}
  ITCH_USER: ${{ secrets.ITCH_USER }}
  PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
on:
  push:
    branches: [main]
jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export game
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ env.PAT }}
      - name: Export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ${{ steps.export.outputs.archive_directory }}/*
      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep "^## \[.*]" ChangeLog.md | head -1 | sed -e 's/## \[//' | sed -e 's/\].*//')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Get ChangeLog
        id: get_changelog
        run: |
          VERSIONS=$(grep "^## \[.*]" ChangeLog.md)
          FIRST_TWO=$(echo "$VERSIONS" | head -2)
          START=$(echo "$FIRST_TWO" | head -1 | sed -e 's/[]\/$*.^[]/\\&/g')
          END=$(echo "$FIRST_TWO" | tail -1 | sed -e 's/[]\/$*.^[]/\\&/g')
          BODY=$(sed -n -r "/$START/,/$END/p" ChangeLog.md | head -n -1)
          echo 'CHANGELOG<<EOF' >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Unzip Web artifact
        run: unzip ${{ steps.export.outputs.archive_directory }}/web.zip -d web
      - name: Enable COEP/COOP headers
        run: |
          curl https://raw.githubusercontent.com/gzuidhof/coi-serviceworker/master/coi-serviceworker.min.js -o web/coi-serviceworker.js
          echo '<script src="coi-serviceworker.js"></script>' >> web/index.html
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: github-pages
          path: web
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.get_changelog.outputs.CHANGELOG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get_version.outputs.VERSION }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
  deploy-pages:
    needs: export_game
    permissions: write-all
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: github-pages
      - name: Upload Pages artifact
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: github-pages
  deploy-itch:
    needs: export_game
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./
      - name: Deploy Windows build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ env.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: windows.zip
      - name: Deploy Linux build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ env.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: linux.zip
      - name: Deploy macOS build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ env.BUTLER_CREDENTIALS }}
          CHANNEL: osx
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: macos.zip
      - name: Deploy web build
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ env.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: web.zip
